<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <RootNamespace>MSECS.Site.Api</RootNamespace>
    <UserSecretsId>msecs-site-api</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\MSECS.Site.Application\MSECS.Site.Application.csproj" />
    <ProjectReference Include="..\MSECS.Site.Infrastructure\MSECS.Site.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\Shared\MSECS.BuildingBlocks\MSECS.BuildingBlocks.csproj" />
  </ItemGroup>
</Project>
