<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <RootNamespace>MSECS.Telemetry.Api</RootNamespace>
    <UserSecretsId>msecs-telemetry-api</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\MSECS.Telemetry.Application\MSECS.Telemetry.Application.csproj" />
    <ProjectReference Include="..\MSECS.Telemetry.Infrastructure\MSECS.Telemetry.Infrastructure.csproj" />
    <ProjectReference Include="..\MSECS.Telemetry.ProtocolAdapters\MSECS.Telemetry.ProtocolAdapters.csproj" />
    <ProjectReference Include="..\..\..\Shared\MSECS.BuildingBlocks\MSECS.BuildingBlocks.csproj" />
  </ItemGroup>
</Project>
